on ch11, getting table name error 'does not exist' but it exists!
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: posts [SQL: 'SELECT posts.id AS posts_id, posts.timestamp AS posts_timestamp, posts.body AS posts_body, posts.author_id AS posts_author_id \nFROM posts ORDER BY posts.timestamp DESC']

note: table is empty